### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CatarinaBrendel** [CatarinaBrendel/mwar#1]
# TODO

1. Login Page
- [x] Fix Responsive medium screens - first div behaves weirdly
- [x] Fix nav in medium screens - button on right disappear to the right 
- [x] Align top/bottom margin of <main>
- [x] Insert LOGO

2. Main Page
- [x] Implement Responsive on small screens
- [x] Check Responsive on medium screens
- [x] Implement float side menu (?)
- [ ] Maybe implement local storage function (simple)
- [x] Fix character counter to reset after the input
- [x] Fix User-tag size (not suppose to grow with new messages)

3. Log out
- [ ] Implement a log out page
